### ISSUE TITLE
why random action?

### ISSUE THREAD

**Issue by sezan92** [Three-agents/Actor-Critic-TF#1]
Hello, Thanks for a really easy to read code. But I was confused by this method.
```    def take_action(self, state):
        """Take the action"""
        action_probs = self.actor.predict(state)
        action = np.random.choice(np.arange(len(action_probs)), p=action_probs)
return action
```
why are you taking random action ? shouldnt we take action of maximum probability ?

**Comment by mgsalem** [comment]
in actor-critic the action is sampled from the actions distribution. not just greedy choice (for exploration)
